
#### DataFrame

* Creating DataFrames from dictionaries
* Creating DataFrames from lists
* Understanding rows and columns

---

### 3. Reading Data

* `pd.read_csv()`
* `pd.read_excel()`
* Viewing datasets

```python
df.head()
df.tail()
df.sample()
```

---

### 4. Dataset Information

```python
df.shape
df.columns
df.info()
df.describe()
```

Understand:

* Number of rows and columns
* Data types
* Missing values
* Statistical summary

---

### 5. Selecting Data

#### Single Column

```python
df["column"]
```

#### Multiple Columns

```python
df[["col1", "col2"]]
```

#### Rows

```python
df.loc[]
df.iloc[]
```

---

### 6. Filtering Data

Examples:

```python
df[df["Age"] > 25]
df[df["Salary"] > 50000]
```

Combining conditions:

```python
(df["Age"] > 25) & (df["Salary"] > 50000)
```

---

### 7. Sorting Data

```python
df.sort_values()
```

Sort by:

* Single column
* Multiple columns
* Ascending/Descending

---

### 8. Basic Aggregations

```python
df["Salary"].mean()
df["Salary"].sum()
df["Salary"].max()
df["Salary"].min()
df["Salary"].count()
```

---

### 9. Handling Missing Values

```python
df.isnull()
df.isnull().sum()
df.dropna()
df.fillna()
```

---

### 10. Exporting Data

```python
df.to_csv()
```

Save processed datasets.

---

In [1]:
import pandas as pd

In [3]:
l = [1, 2, 3, 4, 5]
l2 = [1, 2, 3, 4, 5]
s = pd.Series(l)
s2 = pd.Series(l2)
print(s)
print(s2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
# Creating a Series with custom indices

s3 = pd.Series(l, index=['a', 'b', 'c', 'd', 'e'])
print(s3)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'city': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)

In [23]:
df = pd.read_csv("data/sample.csv")

In [24]:
df.head()
df.tail()
df.sample(5)

df.shape
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 26 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   id                                  1000 non-null   int64
 1   age                                 1000 non-null   int64
 2   alcohol_consumption_per_week        1000 non-null   int64
 3   physical_activity_minutes_per_week  1000 non-null   int64
 4   diet_score                          1000 non-null   float64
 5   sleep_hours_per_day                 1000 non-null   float64
 6   screen_time_hours_per_day           1000 non-null   float64
 7   bmi                                 1000 non-null   float64
 8   waist_to_hip_ratio                  1000 non-null   float64
 9   systolic_bp                         1000 non-null   int64
 10  diastolic_bp                        1000 non-null   int64
 11  heart_rate                          1000 non-null   int64
 12  cholesterol_total                   1000 non-null   int64
 13  hdl_cholesterol                     1000 non-null   int64
 14  ldl_cholesterol                     1000 non-null   int64
 15  triglycerides                       1000 non-null   int64
 16  gender                              1000 non-null   object
 17  ethnicity                           1000 non-null   object
 18  education_level                     1000 non-null   object
 19  income_level                        1000 non-null   object
 20  smoking_status                      1000 non-null   object
 21  employment_status                   1000 non-null   object
 22  family_history_diabetes             1000 non-null   int64
 23  hypertension_history                1000 non-null   int64
 24  cardiovascular_history              1000 non-null   int64
 25  diagnosed_diabetes                  1000 non-null   float64
dtypes: float64(6), int64(14), object(6)
memory usage: 203.3+ KB

,id,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,diastolic_bp,heart_rate,cholesterol_total,hdl_cholesterol,ldl_cholesterol,triglycerides,family_history_diabetes,hypertension_history,cardiovascular_history,diagnosed_diabetes
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000,1000.000000,1000.00000,1000.000000,1000.000000
mean,499.500000,49.88300,2.022000,82.135000,5.917600,7.015600,6.022400,25.809800,0.857530,116.161000,75.619000,69.896000,186.784000,53.857000,102.595000,121.9920,0.151000,0.17700,0.040000,0.595000
std,288.819436,11.77038,1.004253,56.690074,1.457599,0.908605,1.988928,2.852167,0.038011,10.694459,6.763696,7.049885,16.723008,8.202428,18.688666,24.0883,0.358228,0.38186,0.196057,0.491138
min,0.000000,19.00000,1.000000,4.000000,1.700000,3.800000,1.200000,17.600000,0.740000,91.000000,57.000000,49.000000,144.000000,29.000000,52.000000,38.0000,0.000000,0.00000,0.000000,0.000000
25%,249.750000,42.00000,1.000000,48.750000,4.900000,6.400000,4.500000,23.800000,0.830000,108.000000,71.000000,65.000000,175.000000,48.000000,89.000000,107.0000,0.000000,0.00000,0.000000,0.000000
50%,499.500000,50.00000,2.000000,70.000000,5.900000,7.000000,6.000000,25.800000,0.860000,117.000000,76.000000,70.000000,187.000000,54.000000,102.000000,122.0000,0.000000,0.00000,0.000000,1.000000
75%,749.250000,58.00000,3.000000,97.250000,6.900000,7.600000,7.425000,27.700000,0.880000,124.000000,80.000000,75.000000,199.000000,59.000000,116.000000,137.0000,0.000000,0.00000,0.000000,1.000000
max,999.000000,84.00000,6.000000,551.000000,9.700000,9.900000,12.500000,34.100000,0.970000,146.000000,96.000000,89.000000,235.000000,80.000000,165.000000,226.0000,1.000000,1.00000,1.000000,1.000000

In [25]:
df["age"]

df["bmi"]

df[["age", "bmi", "systolic_bp"]]

     age   bmi  systolic_bp
0     31  33.4          112
1     50  23.8          120
2     32  24.1           95
3     54  26.6          121
4     54  28.8          108
..   ...   ...          ...
995   61  23.7          121
996   54  22.7          112
997   22  28.5          115
998   34  27.5          114
999   42  21.3          110

[1000 rows x 3 columns]

In [14]:
a.age

0      31
1      50
2      32
3      54
4      54
       ..
995    61
996    54
997    22
998    34
999    42
Name: age, Length: 1000, dtype: int64

In [26]:
df.loc[0]

df.iloc[0]

df.iloc[0:10]

,id,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,...,gender,ethnicity,education_level,income_level,smoking_status,employment_status,family_history_diabetes,hypertension_history,cardiovascular_history,diagnosed_diabetes
0,0,31,1,45,7.7,6.8,6.1,33.4,0.93,112,...,Female,Hispanic,Highschool,Lower-Middle,Current,Employed,0,0,0,1.0
1,1,50,2,73,5.7,6.5,5.8,23.8,0.83,120,...,Female,White,Highschool,Upper-Middle,Never,Employed,0,0,0,1.0
2,2,32,3,158,8.5,7.4,9.1,24.1,0.83,95,...,Male,Hispanic,Highschool,Lower-Middle,Never,Retired,0,0,0,0.0
3,3,54,3,77,4.6,7.0,9.2,26.6,0.83,121,...,Female,White,Highschool,Lower-Middle,Current,Employed,0,1,0,1.0
4,4,54,1,55,5.7,6.2,5.1,28.8,0.90,108,...,Male,White,Highschool,Upper-Middle,Never,Retired,0,1,0,1.0
5,5,42,1,100,4.4,6.4,5.3,25.5,0.84,111,...,Female,White,Highschool,Lower-Middle,Never,Retired,0,0,0,0.0
6,6,41,2,148,3.4,5.6,3.7,27.9,0.89,130,...,Female,White,Graduate,Lower-Middle,Current,Employed,0,0,0,1.0
7,7,51,3,102,4.0,7.3,5.5,27.1,0.83,125,...,Male,Asian,Highschool,Low,Never,Employed,1,0,0,1.0
8,8,34,2,44,2.7,7.0,7.9,22.6,0.81,120,...,Male,White,Highschool,Lower-Middle,Never,Employed,0,0,0,0.0
9,9,44,1,36,5.8,5.7,6.6,29.3,0.88,110,...,Male,Hispanic,Highschool,Middle,Never,Employed,1,0,0,1.0

In [16]:
a[a['age'] > 30]

,id,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,...,gender,ethnicity,education_level,income_level,smoking_status,employment_status,family_history_diabetes,hypertension_history,cardiovascular_history,diagnosed_diabetes
0,0,31,1,45,7.7,6.8,6.1,33.4,0.93,112,...,Female,Hispanic,Highschool,Lower-Middle,Current,Employed,0,0,0,1.0
1,1,50,2,73,5.7,6.5,5.8,23.8,0.83,120,...,Female,White,Highschool,Upper-Middle,Never,Employed,0,0,0,1.0
2,2,32,3,158,8.5,7.4,9.1,24.1,0.83,95,...,Male,Hispanic,Highschool,Lower-Middle,Never,Retired,0,0,0,0.0
3,3,54,3,77,4.6,7.0,9.2,26.6,0.83,121,...,Female,White,Highschool,Lower-Middle,Current,Employed,0,1,0,1.0
4,4,54,1,55,5.7,6.2,5.1,28.8,0.90,108,...,Male,White,Highschool,Upper-Middle,Never,Retired,0,1,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,994,54,4,46,8.1,7.7,7.1,29.9,0.91,115,...,Male,White,Highschool,Middle,Former,Employed,0,0,0,0.0
995,995,61,1,32,3.7,5.4,4.4,23.7,0.81,121,...,Female,White,Highschool,Upper-Middle,Never,Employed,0,0,0,1.0
996,996,54,1,28,6.2,7.9,6.3,22.7,0.81,112,...,Male,Hispanic,Highschool,Middle,Never,Retired,1,0,0,0.0
998,998,34,1,98,4.8,7.5,7.8,27.5,0.88,114,...,Female,Black,Highschool,Middle,Current,Employed,0,0,0,1.0
999,999,42,2,38,6.1,7.1,5.3,21.3,0.79,110,...,Female,White,Graduate,Lower-Middle,Never,Retired,0,0,0,1.0

In [27]:
df[df["age"] > 50]

,id,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,...,gender,ethnicity,education_level,income_level,smoking_status,employment_status,family_history_diabetes,hypertension_history,cardiovascular_history,diagnosed_diabetes
3,3,54,3,77,4.6,7.0,9.2,26.6,0.83,121,...,Female,White,Highschool,Lower-Middle,Current,Employed,0,1,0,1.0
4,4,54,1,55,5.7,6.2,5.1,28.8,0.90,108,...,Male,White,Highschool,Upper-Middle,Never,Retired,0,1,0,1.0
7,7,51,3,102,4.0,7.3,5.5,27.1,0.83,125,...,Male,Asian,Highschool,Low,Never,Employed,1,0,0,1.0
11,11,54,2,58,6.2,7.7,7.2,23.3,0.81,124,...,Male,White,Highschool,Low,Never,Employed,0,0,0,0.0
12,12,63,2,44,8.0,6.0,6.8,26.6,0.88,119,...,Female,White,Postgraduate,Middle,Never,Employed,1,0,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,991,69,2,261,3.3,8.9,8.4,23.7,0.85,124,...,Female,Asian,Graduate,Upper-Middle,Never,Employed,0,1,0,0.0
993,993,58,2,189,4.9,8.6,7.6,26.7,0.87,117,...,Female,White,Graduate,Lower-Middle,Never,Employed,0,0,0,1.0
994,994,54,4,46,8.1,7.7,7.1,29.9,0.91,115,...,Male,White,Highschool,Middle,Former,Employed,0,0,0,0.0
995,995,61,1,32,3.7,5.4,4.4,23.7,0.81,121,...,Female,White,Highschool,Upper-Middle,Never,Employed,0,0,0,1.0
996,996,54,1,28,6.2,7.9,6.3,22.7,0.81,112,...,Male,Hispanic,Highschool,Middle,Never,Retired,1,0,0,0.0

In [28]:
df[
    (df["family_history_diabetes"] == 1) &
    (df["diagnosed_diabetes"] == 1)
]

,id,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,...,gender,ethnicity,education_level,income_level,smoking_status,employment_status,family_history_diabetes,hypertension_history,cardiovascular_history,diagnosed_diabetes
7,7,51,3,102,4.0,7.3,5.5,27.1,0.83,125,...,Male,Asian,Highschool,Low,Never,Employed,1,0,0,1.0
9,9,44,1,36,5.8,5.7,6.6,29.3,0.88,110,...,Male,Hispanic,Highschool,Middle,Never,Employed,1,0,0,1.0
12,12,63,2,44,8.0,6.0,6.8,26.6,0.88,119,...,Female,White,Postgraduate,Middle,Never,Employed,1,0,0,1.0
18,18,43,2,53,4.1,7.4,6.4,23.8,0.85,120,...,Female,White,Highschool,Lower-Middle,Former,Retired,1,0,0,1.0
22,22,45,4,94,5.4,6.6,7.2,28.4,0.87,123,...,Female,White,Highschool,Middle,Former,Employed,1,0,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,944,48,1,32,3.9,8.1,8.7,27.6,0.83,132,...,Female,Black,Highschool,Low,Never,Employed,1,1,0,1.0
953,953,56,3,64,7.7,5.0,9.5,25.3,0.88,115,...,Female,White,Highschool,Middle,Former,Employed,1,0,0,1.0
960,960,26,4,123,7.8,5.5,7.8,27.7,0.87,109,...,Female,White,Highschool,Lower-Middle,Former,Employed,1,0,0,1.0
972,972,29,2,62,2.3,6.0,4.9,30.4,0.90,99,...,Female,White,Highschool,Middle,Current,Employed,1,0,0,1.0
985,985,38,3,38,2.6,5.8,7.1,26.7,0.85,107,...,Female,Hispanic,Highschool,Middle,Former,Employed,1,0,0,1.0

In [29]:
df["age"].mean()

df["bmi"].mean()

df["cholesterol_total"].max()

df["heart_rate"].min()

df["age"].median()

df["bmi"].std()

np.float64(2.852167389691359)

In [30]:
df.sort_values("age")

df.sort_values("bmi", ascending=False)

df.sort_values(
    ["age", "bmi"],
    ascending=False
)

,id,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,...,gender,ethnicity,education_level,income_level,smoking_status,employment_status,family_history_diabetes,hypertension_history,cardiovascular_history,diagnosed_diabetes
132,132,84,4,55,2.8,7.7,4.8,30.9,0.92,125,...,Male,Other,Highschool,Upper-Middle,Never,Employed,0,0,1,0.0
659,659,82,2,39,7.6,7.0,5.8,25.9,0.89,123,...,Female,White,Postgraduate,Low,Former,Employed,0,1,0,1.0
850,850,81,1,64,4.1,7.8,6.6,25.0,0.89,109,...,Female,Hispanic,Highschool,Middle,Former,Retired,0,1,0,1.0
864,864,80,3,122,6.0,6.9,6.8,25.0,0.88,130,...,Female,Hispanic,Highschool,Lower-Middle,Former,Unemployed,0,0,0,0.0
267,267,80,1,112,9.2,7.1,4.1,21.3,0.82,134,...,Male,White,Postgraduate,Low,Never,Retired,0,0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816,816,21,1,91,4.1,7.7,4.1,24.5,0.84,108,...,Female,White,Highschool,Middle,Former,Employed,0,0,0,0.0
309,309,20,3,23,5.5,5.8,3.7,27.3,0.88,109,...,Female,White,Highschool,Middle,Former,Student,0,0,0,1.0
449,449,20,2,52,5.6,6.7,7.9,21.3,0.76,103,...,Female,White,Graduate,Upper-Middle,Never,Employed,0,1,0,0.0
31,31,20,2,59,7.7,8.8,10.1,20.8,0.85,98,...,Female,Hispanic,Highschool,Lower-Middle,Never,Retired,1,0,0,1.0
591,591,19,1,107,6.2,7.8,7.6,22.3,0.77,100,...,Female,Black,Graduate,Lower-Middle,Never,Employed,0,0,0,1.0

In [31]:
df.isnull()

df.isnull().sum()

df.isnull().any()

id                                    False
age                                   False
alcohol_consumption_per_week          False
physical_activity_minutes_per_week    False
diet_score                            False
sleep_hours_per_day                   False
screen_time_hours_per_day             False
bmi                                   False
waist_to_hip_ratio                    False
systolic_bp                           False
diastolic_bp                          False
heart_rate                            False
cholesterol_total                     False
hdl_cholesterol                       False
ldl_cholesterol                       False
triglycerides                         False
gender                                False
ethnicity                             False
education_level                       False
income_level                          False
smoking_status                        False
employment_status                     False
family_history_diabetes               False
hypertension_history                  False
cardiovascular_history                False
diagnosed_diabetes                    False
dtype: bool

In [32]:
df.isnull().sum()[df.isnull().sum() > 0]

Series([], dtype: int64)

In [33]:
df["gender"].unique()

df["ethnicity"].unique()

df["smoking_status"].unique()

df["education_level"].unique()

array(['Highschool', 'Graduate', 'Postgraduate', 'No formal'],
      dtype=object)

In [34]:
df["gender"].value_counts()

df["smoking_status"].value_counts()

smoking_status
Never      690
Former     163
Current    147
Name: count, dtype: int64

In [35]:
df["bp_difference"] = (
    df["systolic_bp"] -
    df["diastolic_bp"]
)

In [36]:
df = df.dropna()

In [37]:
df.to_csv("data/cleaned_data.csv", index=False)